name: "SecTool install action"
description: "Install and use SecTool in GitHub Actions"
author: "A13Labs"

inputs:
  version:
    description: "The version to install"
    required: true
    default: 0.0.6

runs:
  using: "node20"
  main: "index.js"

branding:
  icon: "terminal"
  color: "blue"
